# Configurazione Cosmos DB con API MongoDB
spring.data.mongodb.uri=mongodb+srv://Karmin:Bakugan8!@logbook-fitness-cluster.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000