name: Azure Static Web Apps CI/CD - React with Nx

on:
  push:
    branches: ["frontend"]
  pull_request:
    branches: ["frontend"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Nx
        run: |
          npm run build
          # Verifica che la build sia stata creata
          [ -d dist/apps/myapp/exported ] || (echo "Build failed" && exit 1)

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'apps/myapp/src'  # Percorso dei sorgenti
          output_location: 'dist/apps/myapp/exported'  # Percorso di output Nx
          skip_app_build: true
          is_static_export: true  # Cruciale per deploy con Nx
          app_artifact_location: 'dist/apps/myapp/exported'